Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "Tapping" "on"             # 启用轻触点击
    Option "NaturalScrolling" "false"  # 启用自然滚动
    Option "ClickMethod" "clickfinger" # 双指右键
EndSection
