[window]
opacity = 0.8

[font]
size = 16

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Underline", blinking = "On"}
