#!/bin/bash

cpu=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')


if [ $(echo "scale=1; $cpu > 50" | bc) -eq 1 ]; then
  color="#ff0000"
elif [ $(echo "scale=1; $cpu > 20" | bc) -eq 1 ]; then
  color="#ffff00"
else
  color="#00ff00"
fi

echo "$cpu%"
echo ""
echo $color
